name: bug_identifier
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.0.0
  go_router: ^13.0.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  camera: ^0.10.5+9
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.2
  http: ^1.1.2
  flutter_markdown: ^0.6.18+2
  collection: ^1.18.0
  permission_handler: ^11.1.0
  sqflite_common_ffi_web: ^0.4.5+4
  share_plus: ^10.1.4
  device_info_plus: ^11.5.0
  purchases_flutter: ^8.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/paywall/
    - assets/icon/
    - assets/config/
    - assets/fonts/
    - assets/fonts/Lora/
    - assets/fonts/Lora/static/
    - assets/fonts/Open_Sans/
    - assets/fonts/Open_Sans/static/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/logo.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icon/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/logo.png"
